---@type table
local M = {}

M.detect_backend_tool_commands = {
	zig = {
		"build\tzig build",
		"fmt\tzig fmt $file",
		"fetch\tzig fetch $zignite_args",
		"run\tzig run $file",
	},
	go = {
		"build\tgo build",
		"env\tgo env",
		"fmt\tgo fmt ./...",
	},
	cargo = {
		"build\tcargo build",
		"check\tcargo check",
		"run\tcargo run",
	},
	odin = {
		"build\todin build .",
		"run\todin run .",
		"test\todin test .",
	},
}

M.project_backend_lines = {
	make = {
		"COMMAND\tbuild\tmake",
		"COMMAND\tbench\tmake bench",
		"COMMAND\ttest\tmake test",
	},
	["make-auto"] = {
		"COMMAND\tbuild\tmake",
		"COMMAND\tbench\tmake bench",
		"COMMAND\ttest\tmake test",
	},
	["package-json"] = {
		"COMMAND\tinstall\tnpm install",
		"COMMAND\tdev\tnpm run dev",
		"COMMAND\tlive\tnpm run dev",
		"COMMAND\tbuild\tnpm run build",
	},
	["package-json-auto"] = {
		"COMMAND\tinstall\tnpm install",
		"COMMAND\tdev\tnpm run dev",
		"COMMAND\tlive\tnpm run dev",
		"COMMAND\tbuild\tnpm run build",
	},
	maven = {
		"COMMAND\tmvn-build\tmvn compile",
		"COMMAND\tmvn-test\tmvn test",
		"COMMAND\tmvn-package\tmvn package",
		"COMMAND\tmvn-run\tmvn spring-boot:run",
		"COMMAND\tbuild\tmvn compile",
		"COMMAND\ttest\tmvn test",
		"COMMAND\trun\tmvn spring-boot:run",
		"PRIMARY_RUN\tmvn spring-boot:run",
		"PREFERRED\tbuild\tmvn compile",
		"PREFERRED\ttest\tmvn test",
		"PREFERRED\trun\tmvn spring-boot:run",
	},
	gradle = {
		"COMMAND\tgradle-build\t./gradlew build",
		"COMMAND\tgradle-test\t./gradlew test",
		"COMMAND\tgradle-clean\t./gradlew clean",
		"COMMAND\tgradle-run\t./gradlew bootRun",
		"COMMAND\tbuild\t./gradlew build",
		"COMMAND\ttest\t./gradlew test",
		"COMMAND\tclean\t./gradlew clean",
		"COMMAND\trun\t./gradlew bootRun",
		"PRIMARY_RUN\t./gradlew bootRun",
		"PREFERRED\tbuild\t./gradlew build",
		"PREFERRED\ttest\t./gradlew test",
		"PREFERRED\trun\t./gradlew bootRun",
	},
	cmake = {
		"COMMAND\tcmake-config\tcmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=1",
		"COMMAND\tcmake-clean\tcmake --build build --target clean",
		"COMMAND\tcmake-debug\t"
			.. "cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=1 && cmake --build build",
		"COMMAND\tcmake-release\t"
			.. "cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=1 && cmake --build build",
		"COMMAND\tcmake-test\tctest --test-dir build",
		"COMMAND\tinstall\tcmake --build build --target install",
		"TARGET\tapp\t1",
		"COMMAND\tcmake-build\tcmake --build build",
		"COMMAND\tcmake-run\tcmake --build build --target app && ./build/bin/app",
		"COMMAND\tcmake-build-app\tcmake --build build --target app",
		"COMMAND\tcmake-run-app\tcmake --build build --target app && ./build/bin/app",
		"RUN_PATH\tapp\t./build/bin/app",
		"PREFERRED\tbuild\tcmake --build build",
		"PRIMARY_TARGET\tapp",
		"PRIMARY_RUN_PATH\t./build/bin/app",
		"PREFERRED\trun\tcmake --build build --target app && ./build/bin/app",
	},
	bazel = {
		"COMMAND\tbazel-query\tbazel query $zignite_args",
		"COMMAND\tbazel-clean\tbazel clean",
		"COMMAND\tbazel-build-all\tbazel build //...",
		"COMMAND\tbazel-test-all\tbazel test //...",
		"TARGET\tcc_binary\tapp\t1\t0\tmain.cc",
		"COMMAND\tbazel-build-app\tbazel build //:app",
		"COMMAND\tbazel-run-app\tbazel run //:app",
		"COMMAND\tbazel-build\tbazel build //:app",
		"COMMAND\tbazel-run\tbazel run //:app",
		"COMMAND\tbuild\tbazel build //:app",
		"COMMAND\trun\tbazel run //:app",
		"PRIMARY_BUILD\tbazel build //:app",
		"PRIMARY_RUN\tbazel run //:app",
		"PREFERRED\tbuild\tbazel build //:app",
		"PREFERRED\trun\tbazel run //:app",
	},
	["bazel-auto"] = {
		"COMMAND\tbazel-query\tbazel query $zignite_args",
		"COMMAND\tbazel-clean\tbazel clean",
		"COMMAND\tbazel-build-all\tbazel build //...",
		"COMMAND\tbazel-test-all\tbazel test //...",
		"TARGET\tcc_binary\tapp\t1\t0\tmain.cc",
		"COMMAND\tbazel-build-app\tbazel build //:app",
		"COMMAND\tbazel-run-app\tbazel run //:app",
		"COMMAND\tbazel-build\tbazel build //:app",
		"COMMAND\tbazel-run\tbazel run //:app",
		"COMMAND\tbuild\tbazel build //:app",
		"COMMAND\trun\tbazel run //:app",
		"PRIMARY_BUILD\tbazel build //:app",
		"PRIMARY_RUN\tbazel run //:app",
		"PREFERRED\tbuild\tbazel build //:app",
		"PREFERRED\trun\tbazel run //:app",
	},
	meson = {
		"COMMAND\tmeson-setup\tmeson setup build",
		"COMMAND\tmeson-clean\tmeson compile -C build --clean",
		"COMMAND\tmeson-test\tmeson test -C build",
		"COMMAND\tinstall\tmeson install -C build",
		"TARGET\tapp\t1",
		"COMMAND\tmeson-build\tmeson compile -C build",
		"COMMAND\tmeson-run\tmeson compile -C build app && ./build/app",
		"COMMAND\tmeson-build-app\tmeson compile -C build app",
		"COMMAND\tmeson-run-app\tmeson compile -C build app && ./build/app",
		"RUN_PATH\tapp\t./build/app",
		"PREFERRED\tbuild\tmeson compile -C build",
		"PRIMARY_TARGET\tapp",
		"PRIMARY_RUN_PATH\t./build/app",
		"PREFERRED\trun\tmeson compile -C build app && ./build/app",
	},
	cargo = {
		"BIN\tapp\t1",
		"COMMAND\tcargo-build-app\tcargo build --bin 'app'",
		"COMMAND\tcargo-run-app\tcargo run --bin 'app'",
		"COMMAND\tcargo-test-app\tcargo test --bin 'app'",
		"PRIMARY_BIN\tapp",
		"PRIMARY_RUN\tcargo run --bin 'app'",
		"PRIMARY_RELEASE_RUN\tcargo run --release --bin 'app'",
		"PREFERRED\trun\tcargo run --bin 'app'",
		"PREFERRED\trelease-run\tcargo run --release --bin 'app'",
	},
	go = {
		"MODULE\texample.com/app",
		"PRIMARY_SELECTOR\t./cmd/app",
		"COMMAND\tgo-build-package\tgo build './cmd/app'",
		"COMMAND\tgo-run-package\tgo run './cmd/app'",
		"COMMAND\tgo-test-package\tgo test './cmd/app'",
		"PRIMARY_BUILD\tgo build './cmd/app'",
		"PRIMARY_RUN\tgo run './cmd/app'",
		"PRIMARY_TEST\tgo test './cmd/app'",
		"PREFERRED\tbuild\tgo build './cmd/app'",
		"PREFERRED\trun\tgo run './cmd/app'",
		"PREFERRED\ttest\tgo test './cmd/app'",
	},
	pyproject = { "TOOL\tuv" },
}

return M
