const std = @import("std");
const common = @import("core/common.zig");

pub fn parseTargets(
    allocator: std.mem.Allocator,
    contents: []const u8,
    names: *std.ArrayList([]u8),
) !void {
    if (isCmakeGeneratedMakefile(contents)) {
        return;
    }

    var lines = std.mem.splitScalar(u8, contents, '\n');
    while (lines.next()) |raw_line| {
        const line = common.stripTrailingCR(raw_line);
        const trimmed = common.trimSpaces(line);
        if (trimmed.len == 0 or trimmed[0] == '#') continue;
        if (line.len > 0 and line[0] == '\t') continue;
        if (looksLikeVariableAssignment(trimmed)) continue;

        const colon_idx = std.mem.indexOfScalar(u8, trimmed, ':') orelse continue;
        const target_segment = common.trimSpaces(trimmed[0..colon_idx]);
        if (target_segment.len == 0) continue;

        var target_it = std.mem.tokenizeScalar(u8, target_segment, ' ');
        while (target_it.next()) |raw_target| {
            const target = common.trimSpaces(raw_target);
            if (!isValidMakeTarget(target)) continue;
            try common.pushUniqueName(allocator, names, target);
        }
    }
}

fn isCmakeGeneratedMakefile(contents: []const u8) bool {
    return std.mem.indexOf(u8, contents, "CMAKE generated file: DO NOT EDIT!") != null
        or std.mem.indexOf(u8, contents, "Generated by \"Unix Makefiles\" Generator") != null;
}

fn looksLikeVariableAssignment(line: []const u8) bool {
    const eq_idx = std.mem.indexOfScalar(u8, line, '=') orelse return false;
    if (eq_idx == 0) return false;
    const prefix = common.trimSpaces(line[0..eq_idx]);
    if (prefix.len == 0) return false;
    const last = prefix[prefix.len - 1];
    if (last == ':' or last == '+' or last == '?') {
        return isIdentifierPrefix(prefix[0 .. prefix.len - 1]);
    }
    return isIdentifierPrefix(prefix);
}

fn isIdentifierPrefix(text: []const u8) bool {
    if (text.len == 0) return false;
    for (text) |ch| {
        if (!(std.ascii.isAlphanumeric(ch) or ch == '_' or ch == '.' or ch == '-')) {
            return false;
        }
    }
    return true;
}

fn isValidMakeTarget(target: []const u8) bool {
    if (target.len == 0) return false;
    if (std.mem.eql(u8, target, "|")) return false;
    if (target[0] == '.') return false;
    if (std.mem.indexOfScalar(u8, target, '%') != null) return false;
    if (std.mem.indexOf(u8, target, "$(") != null) return false;
    return true;
}

test "parse make targets" {
    const allocator = std.testing.allocator;
    var names: std.ArrayList([]u8) = .empty;
    defer {
        for (names.items) |name| allocator.free(name);
        names.deinit(allocator);
    }

    try parseTargets(
        allocator,
        "build: test\n\t@echo ok\nVAR := value\nbench:\n",
        &names,
    );

    try std.testing.expectEqual(@as(usize, 3), names.items.len);
    try std.testing.expectEqualStrings("build", names.items[0]);
    try std.testing.expectEqualStrings("test", names.items[1]);
    try std.testing.expectEqualStrings("bench", names.items[2]);
}

test "skip cmake generated makefile" {
    const allocator = std.testing.allocator;
    var names: std.ArrayList([]u8) = .empty;
    defer {
        for (names.items) |name| allocator.free(name);
        names.deinit(allocator);
    }

    try parseTargets(
        allocator,
        \\# CMAKE generated file: DO NOT EDIT!
        \\all:
    , &names);
    try std.testing.expectEqual(@as(usize, 0), names.items.len);
}
